[package]
name = "galfus-host-embedded-hal"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
galfus-bytecode = { path = "../../engine/galfus-bytecode", default-features = false }
galfus-contract = { path = "../../engine/galfus-contract", default-features = false }
galfus-runtime = { path = "../../engine/galfus-runtime", default-features = false }
