[package]
name = "galfus-benchmark"
version = "0.0.0"
edition = "2024"

[dependencies]
sysinfo = "0.30"
cli-table = "0.4"
plotly = { version = "0.14.1", features = ["plotly_embed_js"] }
regex = "1.13"
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
galfus-contract = { path = "../../engine/galfus-contract" }
galfus-host-native = { path = "../galfus-host-native" }
galfus-runtime = { path = "../../engine/galfus-runtime" }
galfus-workspace = { path = "../../engine/galfus-workspace" }
