[package]
name = "galfus-host-web"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
galfus-bytecode = { path = "../../engine/galfus-bytecode" }
galfus-contract = { path = "../../engine/galfus-contract" }
galfus-runtime = { path = "../../engine/galfus-runtime" }
