[package]
name = "galfus-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
galfus-core = { path = "../../engine/galfus-core" }
galfus-contract = { path = "../../engine/galfus-contract" }
galfus-runtime = { path = "../../engine/galfus-runtime" }
galfus-workspace = { path = "../../engine/galfus-workspace" }
galfus-host-native = { path = "../galfus-host-native" }

anyhow.workspace = true
tracing.workspace = true

clap = { version = "4.6", features = ["derive"] }
tracing-subscriber = "0.3"
dialoguer = "0.11"
