[package]
name = "galfus-contract"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
galfus-core = { path = "../galfus-core" }
serde = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
toml = { workspace = true }

[dev-dependencies]
galfus-core = { path = "../galfus-core" }
galfus-frontend = { path = "../galfus-frontend" }
