[package]
name = "galfus-host-native"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
metrics = ["galfus-runtime/metrics"]

[dependencies]
galfus-core = { path = "../../engine/galfus-core" }
galfus-bytecode = { path = "../../engine/galfus-bytecode" }
galfus-contract = { path = "../../engine/galfus-contract" }
galfus-runtime = { path = "../../engine/galfus-runtime" }
crossbeam-channel = "0.5"
ureq.workspace = true
tungstenite.workspace = true
url.workspace = true
hyper.workspace = true
hyper-util.workspace = true
http-body-util.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
futures-util.workspace = true

[dev-dependencies]
galfus-workspace = { path = "../../engine/galfus-workspace" }
toml.workspace = true
